### ISSUE TITLE
Errors generated when players join in large numbers

### ISSUE THREAD

**Issue by Coquettishpig** [DecentSoftware-eu/DecentHolograms#125]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

[10:43:26] [Craft Scheduler Thread - 335 - DecentHolograms/ERROR]: Thread Craft Scheduler Thread - 335 - DecentHolograms failed main thread check: Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2417) ~[?:?]
	at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:1869) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntity(EntityUtilities.java:105) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:408) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecific(BukkitConverters.java:812) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecific(BukkitConverters.java:797) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:301) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:251) ~[ProtocolLib.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.WrapperPlayServerSpawnEntity.getEntity(WrapperPlayServerSpawnEntity.java:128) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.WrapperPlayServerSpawnEntity.getEntity(WrapperPlayServerSpawnEntity.java:140) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl.isHologram(ProtocolLibHookImpl.java:372) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl.access$100(ProtocolLibHookImpl.java:38) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.hook.protocollib.packets.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:172) ~[GadgetsMenu.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:208) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:193) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:551) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:525) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at eu.decentsoftware.holograms.api.utils.reflect.ReflectMethod.invoke(ReflectMethod.java:35) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.nms.NMS.sendPacket(NMS.java:231) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntity(NMS_1_17.java:234) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityLiving(NMS_1_17.java:273) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.nms.versions.NMS_1_17.showFakeEntityArmorStand(NMS_1_17.java:342) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.holograms.HologramLine.show(HologramLine.java:417) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$showPageTo$4(Hologram.java:643) ~[DecentHolograms-2.8.1.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at eu.decentsoftware.holograms.api.holograms.Hologram.showPageTo(Hologram.java:643) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.holograms.Hologram.show(Hologram.java:630) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:89) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:71) ~[DecentHolograms-2.8.1.jar:?]
	at eu.decentsoftware.holograms.api.player.PlayerListener.lambda$onJoin$0(PlayerListener.java:23) ~[DecentHolograms-2.8.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-448]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Solution

holograms.api or ProtocolLib
[2023-04-07-2.log](https://github.com/DecentSoftware-eu/DecentHolograms/files/11175755/2023-04-07-2.log)

### Server Version

git-Paper-448 (MC: 1.19.3)

### Client Version

1.19.3

### Plugin Version

2.8.1

### Log

I can't use than, log in top

**Comment by d0by1** [comment]
Hey! The stack trace seems to be pointing to GadgetsMenu. Basically, when DH sends packets asynchronously to update holograms, GadgetsMenu catches these packets and does something with them, which then causes the AsyncCatcher in Spigot to throw an exception. I think that GadgetsMenu doesn't check if it's on the Main thread when it catches the packets and does something, that can only be done on the main thread (not async). 

Try to report this to the developer of GadgetsMenu. They might know more about how their packet listener works. I can't really do anything about this though, it's the GadgetsMenu's packet listener causing the exception to be thrown, according to the provided stack trace.
