### ISSUE TITLE
Hologram Error

### ISSUE THREAD

**Issue by Dreandor** [DecentSoftware-eu/DecentHolograms#136]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms - I did
2. Do something - I created a Hologram with an Placeholder
3. Do something else - I relogged and then the Placeholder didn't worked anymore and I got this Error in Console
4. This happens - 
! [Mo. 18:34:26 WARN  DecentHolograms] Plugin DecentHolograms v2.8.1 generated an exception while executing task 523850
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
    at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
    at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.holograms.HologramManager.hideAll(HologramManager.java:212)
    at DecentHolograms-2.8.1.jar//eu.decentsoftware.holograms.api.player.PlayerListener.lambda$onTeleport$4(PlayerListener.java:46)
    at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

### Solution

Maybe the Plugin has Problems with Placeholder

### Server Version

Paper #538

### Client Version

1.19.4

### Plugin Version

2.8.1

### Log

https://pastebin.com/1tyK041F

**Comment by Andre601** [comment]
People get this a lot lately. Not sure what's the actual cause of this tho.

**Comment by d0by1** [comment]
Hello, this should now be fixed in version 2.8.2, thanks for reporting it!
