### ISSUE TITLE
MC 1.20.2 unsupported

### ISSUE THREAD

**Issue by SlimeDog** [DecentSoftware-eu/DecentHolograms#156]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Update to Spigot 1.20.2
2. Start server
3. Read log

```
[11:38:54] [Server thread/INFO]: [DecentHolograms] Loading DecentHolograms v2.8.3
[11:38:54] [Server thread/ERROR]: [DecentHolograms] Unsupported server version: v1_20_R2
[11:38:54] [Server thread/ERROR]: [DecentHolograms] Plugin will be disabled.
```
(and then it tries to enable anyway)
```
[11:39:35] [Server thread/INFO]: [DecentHolograms] Enabling DecentHolograms v2.8.3
[11:39:35] [Server thread/ERROR]: Error occurred while enabling DecentHolograms v2.8.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at eu.decentsoftware.holograms.api.DecentHolograms.enable(DecentHolograms.java:75) ~[DecentHolograms-2.8.3.jar:?]
        at eu.decentsoftware.holograms.api.DecentHologramsAPI.onEnable(DecentHologramsAPI.java:51) ~[DecentHolograms-2.8.3.jar:?]
        at eu.decentsoftware.holograms.plugin.DecentHologramsPlugin.onEnable(DecentHologramsPlugin.java:23) ~[DecentHolograms-2.8.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3882-Spigot-17ca32d-452fcb5]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "eu.decentsoftware.holograms.api.utils.reflect.Version.getMinor()" because "eu.decentsoftware.holograms.api.utils.reflect.Version.CURRENT" is null
        at eu.decentsoftware.holograms.api.utils.reflect.Version.afterOrEqual(Version.java:82) ~[DecentHolograms-2.8.3.jar:?]
        at eu.decentsoftware.holograms.api.nms.NMS.<clinit>(NMS.java:39) ~[DecentHolograms-2.8.3.jar:?]
        ... 14 more
```

### Solution

Update to support MC 1.20.2

### Server Version

Spigot 1.20.2-3788

### Client Version

1.20.2

### Plugin Version

2.8.3

### Log

N/A

**Comment by Outfluencer** [comment]
Bump

**Comment by Draghonir** [comment]
bump x)

**Comment by d0by1** [comment]
Version 2.8.4 supports 1.20.2. I will now close this issue.

**Comment by SlimeDog** [comment]
Confirmed with Paper 1.20.2-206. Thanks.
