### ISSUE TITLE
decent holograms error

### ISSUE THREAD

**Issue by SinestroCZE** [DecentSoftware-eu/DecentHolograms#201]
### Just making sure

- [ ] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Hello, i have a problem with your plugin DecentHolograms

Here is output error from console
-----------------------------------------------
[11:31:18] [Server thread/WARN]: [DecentHolograms] Failed to modify player's pipeline. (SinestroCZ)
java.lang.NullPointerException: Cannot invoke "eu.decentsoftware.holograms.api.utils.reflect.ReflectField.getValue(Object)" because "eu.decentsoftware.holograms.api.nms.NMS.PLAYER_CONNECTION_NETWORK_MANAGER_FIELD" is null
        at eu.decentsoftware.holograms.api.nms.NMS.getPipeline(NMS.java:250) ~[?:?]
        at eu.decentsoftware.holograms.api.nms.PacketListener.executeOnPipeline(PacketListener.java:51) ~[?:?]
        at eu.decentsoftware.holograms.api.nms.PacketListener.unhook(PacketListener.java:38) ~[?:?]
        at eu.decentsoftware.holograms.api.listeners.PlayerListener.onQuit(PlayerListener.java:38) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:516) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.network.PlayerConnection.q(PlayerConnection.java:1724) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1711) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.network.NetworkManager.p(NetworkManager.java:611) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:200) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1242) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4056-Spigot-e9ec548-176c0ad]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
---------------------------------------------------------------

### Server Version

1.20.4

### Client Version

1.20.4

### Plugin Version

2.8.6

### Log

nothing

**Comment by Andre601** [comment]
Known issue, unknown fix

**Comment by PirataGu** [comment]
I'm having the same issue + the server doesnt let the players in because of this. Fix please

**Comment by Andre601** [comment]
Something won't just stop working out of nowhere without changes, so you made a change.

Please share your server type and version. OP, please share server type.

**Comment by SinestroCZE** [comment]
> Something won't just stop working out of nowhere without changes, so you made a change.
> 
> Please share your server type and version. OP, please share server type.

Iam the server owner. Version: 1.20.4 on Spigot. Hosting: Dedicated server.

**Comment by PirataGu** [comment]
Literally I dont change holograms for about 5 days

**Comment by Andre601** [comment]
Try paper.
People report the issue to be fixed on it compared to Spigot

**Comment by PirataGu** [comment]
I use Purpur
I'll try to see if something change on Velocity

**Comment by PirataGu** [comment]
Just tested everything. Problaly a proxy error... strange cause I didnt change anything these last months

**Comment by SinestroCZE** [comment]
> Just tested everything. Problaly a proxy error... strange cause I didnt change anything these last months

Functionally it has no effect, I haven't registered any yet.  But just for information I posted it here, as you say maybe it's just the bungeecord doing it, functionally it's fine.  Just to let you know for the future.

**Comment by SinestroCZE** [comment]
Anyway, I have to appreciate the quick response of the creator, a huge thumbs up for this.  You are doing a great job, good luck in the future

**Comment by Eddyp2** [comment]
What was the fix?

**Comment by d0by1** [comment]
I will now close this issue to streamline the issue tracker. If you witness the problem again, feel free to create a new issue. I did make some changes to this in 2.8.7 and it might already be fixed.
