### ISSUE TITLE
1.20.6 support

### ISSUE THREAD

**Issue by PukPukov** [DecentSoftware-eu/DecentHolograms#209]
### Just making sure

- [x] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Feature

1.20.6 support

**Comment by Link0Darck** [comment]
```
[22:47:30] [Server thread/ERROR]: Error occurred while enabling DecentHolograms v2.8.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at eu.decentsoftware.holograms.api.DecentHolograms.enable(DecentHolograms.java:76) ~[?:?]
        at eu.decentsoftware.holograms.api.DecentHologramsAPI.onEnable(DecentHologramsAPI.java:51) ~[?:?]
        at eu.decentsoftware.holograms.plugin.DecentHologramsPlugin.onEnable(DecentHologramsPlugin.java:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:542) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:456) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4161-Spigot-e2c1eee-6118e53]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "eu.decentsoftware.holograms.api.utils.reflect.Version.getMinor()" because "eu.decentsoftware.holograms.api.utils.reflect.Version.CURRENT" is null
        at eu.decentsoftware.holograms.api.utils.reflect.Version.afterOrEqual(Version.java:84) ~[?:?]
        at eu.decentsoftware.holograms.api.nms.NMS.<clinit>(NMS.java:42) ~[?:?]
        ... 14 more
```

**Comment by PukPukov** [comment]
Maybe someone make pull request? Much better that waiting until main developer wake up.

**Comment by Legoman99573** [comment]
May not be as simple as switch a line.

This no longer functions as of 1.20.5/1.20.6 and it may not be as much of a simple fix since its near impossible to grab a version like ``1_20_R4``.
https://github.com/DecentSoftware-eu/DecentHolograms/blob/e6ac39a4a0d1644e3c724dd7f94f1106196e04a7/src/main/java/eu/decentsoftware/holograms/api/utils/reflect/ReflectionUtil.java#L90

I know there was an announcement in the [Paper Forums](https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/) about workarounds, but not sure on how to adapt it to the current version checks while retaining backwards compatibility.

**Comment by PukPukov** [comment]
No, this is not a problem. As said in this very article, there is method that exists from 2011 in bukkit to get version.

**Comment by Legoman99573** [comment]
If someone has experience with it, they can go at it, but I don't feel like touching anything as I may most likely break backwards compatibility.

**Comment by d0by1** [comment]
Support for 1.20.6 was added in 2.8.7, enjoy!
