### ISSUE TITLE
HoloPlots to errors because of DecentHolograms

### ISSUE THREAD

**Issue by Link0Darck** [DecentSoftware-eu/DecentHolograms#214]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. install and configue plotsquared
3. install HoloPlots
4. Claim plot
![2024-05-19_23 05 24](https://github.com/DecentSoftware-eu/DecentHolograms/assets/28543376/bb2b8bcb-de59-4936-8933-522f5b3a4d99)

### Server Version

This server is running CraftBukkit version 4170-Spigot-342f493-87d0a33 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### Client Version

Minecraft 1.20.6

### Plugin Version

This server is running DecentHolograms v2.8.8 by d0by : https://www.spigotmc.org/resources/96927/

### Log

https://pastebin.com/5PRrBBkq

**Comment by Link0Darck** [comment]
Or else I had this as a bug
```
[03:17:41] [Server thread/ERROR]: Unable to find the constructor for the class 'net.minecraft.world.item.ItemStack'
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.<init>(net.minecraft.nbt.NBTTagCompound)
        at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?]
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.utils.nmsmappings.ObjectCreator.<init>(ObjectCreator.java:36) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.utils.nmsmappings.ObjectCreator.<clinit>(ObjectCreator.java:22) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTContainer.<init>(NBTContainer.java:27) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:610) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[?:?]
        at eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:147) ~[?:?]
        at eu.decentsoftware.holograms.api.DHAPI.addHologramLine(DHAPI.java:353) ~[?:?]
        at com.plotsquared.holoplots.provider.impl.DecentHologramsProvider.createHologram(DecentHologramsProvider.java:32) ~[?:?]
        at com.plotsquared.holoplots.provider.HologramProvider.createOrUpdateHologram(HologramProvider.java:69) ~[?:?]
        at com.plotsquared.holoplots.DefaultHoloPlots.lambda$updatePlot$3(DefaultHoloPlots.java:182) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39) ~[?:?]
        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1397) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[03:17:41] [Server thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[03:17:41] [Server thread/ERROR]: [HoloPlots] Failed to update hologram @ plotworld;0;0
java.util.concurrent.CompletionException: eu.decentsoftware.holograms.libs.nbtapi.NbtApiException: [?][2.12.2]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class net.minecraft.world.item.EnumAnimation
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39) ~[?:?]
        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1397) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: eu.decentsoftware.holograms.libs.nbtapi.NbtApiException: [?][2.12.2]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class net.minecraft.world.item.EnumAnimation
        at eu.decentsoftware.holograms.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:386) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:626) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[?:?]
        at eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:147) ~[?:?]
        at eu.decentsoftware.holograms.api.DHAPI.addHologramLine(DHAPI.java:353) ~[?:?]
        at com.plotsquared.holoplots.provider.impl.DecentHologramsProvider.createHologram(DecentHologramsProvider.java:32) ~[?:?]
        at com.plotsquared.holoplots.provider.HologramProvider.createOrUpdateHologram(HologramProvider.java:69) ~[?:?]
        at com.plotsquared.holoplots.DefaultHoloPlots.lambda$updatePlot$3(DefaultHoloPlots.java:182) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:383) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:626) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[?:?]
        at eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:147) ~[?:?]
        at eu.decentsoftware.holograms.api.DHAPI.addHologramLine(DHAPI.java:353) ~[?:?]
        at com.plotsquared.holoplots.provider.impl.DecentHologramsProvider.createHologram(DecentHologramsProvider.java:32) ~[?:?]
        at com.plotsquared.holoplots.provider.HologramProvider.createOrUpdateHologram(HologramProvider.java:69) ~[?:?]
        at com.plotsquared.holoplots.DefaultHoloPlots.lambda$updatePlot$3(DefaultHoloPlots.java:182) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        ... 11 more
```

**Comment by Andre601** [comment]
> This server is running CraftBukkit version 4170-Spigot-342f493-87d0a33 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

Double check you ACTUALLY use Spigot and not CraftBukkit. Tho, I suggest you use Paper instead for better performance, which may also fix the issue because Spigot had some issues in the past and this could be no difference to that.

**Comment by Link0Darck** [comment]
> > This server is running CraftBukkit version 4170-Spigot-342f493-87d0a33 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
> > You are running the latest version
> 
> Double check you ACTUALLY use Spigot and not CraftBukkit. Tho, I suggest you use Paper instead for better performance, which may also fix the issue because Spigot had some issues in the past and this could be no difference to that.

Good morning,
I use belle est spigot 1.20.6 on my pterodactyl server then I would not use paper for the simple reason that I had a lot of problems thank you in advance for your help

**Comment by d0by1** [comment]
Hello, this seems to be caused by changes made to items in 1.20.5. From what I know so far, there is now an extra step when adding custom NBT to items. I will investigate this further and post an update on this issue when I know more.

For now, removing any items with custom NBT from the holograms should help.

**Comment by d0by1** [comment]
Hi, Item NBT is now supported in Minecraft 1.20.5+ as of DH version 2.8.10.
