### ISSUE TITLE
Failed to modify player's pipeline. (NoSuchElementException/packet_handler)

### ISSUE THREAD

**Issue by andrewkm** [DecentSoftware-eu/DecentHolograms#219]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Looks to happen immediately after the player's login, 
Unknown reproduction.

```
[17:36:00] [Netty Server IO #1/WARN]: [DecentHolograms] Failed to modify player's pipeline. (AusRoona)
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$hook$0(PacketListener.java:30) ~[DecentHolograms-2.8.9.jar:?]
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.api.nms.PacketListener.executeOnPipeline(PacketListener.java:52) ~[DecentHolograms-2.8.9.jar:?]
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$executeOnPipeline$2(PacketListener.java:54) ~[DecentHolograms-2.8.9.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Server Version

Paper version 1.20.6-147-ver/1.20.6@e41d44f

### Client Version

Cannot detect the player's client version nor are they available to ask.

### Plugin Version

2.8.9 - Compiled against (https://github.com/DecentSoftware-eu/DecentHolograms/commit/24af34072820f735efef2c1c62bb8e34b55fd845)

### Log

https://pastebin.com/raw/bC0MWxUV

**Comment by d0by1** [comment]
Hi, I've added additional details to the log message associated with this error in DH 2.8.10. Could you please test the issue in this new version and share the updated log message with me? Thanks!

**Comment by IAISI** [comment]
Still an issue on

```
> ver DecentHolograms
[22:34:48 INFO]: DecentHolograms version 2.8.11
[22:34:48 INFO]: A lightweight yet very powerful hologram plugin with many features and configuration options.
[22:34:48 INFO]: Author: d0by
```

and latest Paper 1.21.1

```
[22:24:32] [Netty Epoll Server IO #2/WARN]: [DecentHolograms] Failed to modify player's pipeline. player: PlayerName, availableElements: [DefaultChannelPipeline$TailContext#0]
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at DecentHolograms.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$hook$0(PacketListener.java:32) ~[DecentHolograms.jar:?]
	at DecentHolograms.jar/eu.decentsoftware.holograms.api.nms.PacketListener.executeOnPipeline(PacketListener.java:54) ~[DecentHolograms.jar:?]
	at DecentHolograms.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$executeOnPipeline$2(PacketListener.java:56) ~[DecentHolograms.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:24:32] [Server thread/INFO]: PlayerName lost connection: Disconnected
```

**Comment by andrewkm** [comment]
Still an issue here on our end via Paper 1.21.3 Build 50.

```
[11:14:15] [Server thread/INFO]: playername[/redacted-IP] logged in with entity id 12769168 at ([rising]2669.5, 74.0, -9596.5)
[11:14:16] [Netty Server IO #0/WARN]: [DecentHolograms] Failed to modify player's pipeline. player: playername, availableElements: [DefaultChannelPipeline$TailContext#0]
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at DecentHolograms-2.8.12.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$hook$0(PacketListener.java:32) ~[DecentHolograms-2.8.12.jar:?]
	at DecentHolograms-2.8.12.jar/eu.decentsoftware.holograms.api.nms.PacketListener.executeOnPipeline(PacketListener.java:54) ~[DecentHolograms-2.8.12.jar:?]
	at DecentHolograms-2.8.12.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$executeOnPipeline$2(PacketListener.java:56) ~[DecentHolograms-2.8.12.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[11:14:16] [Server thread/INFO]: playername lost connection: Kicked for exceeding packet rate limit
```

@d0by1

**Comment by Andre601** [comment]
The last line seems to be interesting:
`playername lost connection: Kicked for exceeding packet rate limit`

**Comment by andrewkm** [comment]
Continues to this day.

```
[11:05:54] [Netty Server IO #2/WARN]: [DecentHolograms] Failed to modify player's pipeline. player: Drdum155, availableElements: [DefaultChannelPipeline$TailContext#0]
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1022) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.DefaultChannelPipeline.internalAdd(DefaultChannelPipeline.java:179) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:246) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at DecentHolograms-2.8.14.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$hook$0(PacketListener.java:32) ~[DecentHolograms-2.8.14.jar:?]
	at DecentHolograms-2.8.14.jar/eu.decentsoftware.holograms.api.nms.PacketListener.executeOnPipeline(PacketListener.java:54) ~[DecentHolograms-2.8.14.jar:?]
	at DecentHolograms-2.8.14.jar/eu.decentsoftware.holograms.api.nms.PacketListener.lambda$executeOnPipeline$2(PacketListener.java:56) ~[DecentHolograms-2.8.14.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

**Comment by Andre601** [comment]
That error at this point can be considered somewhat harmless, as from what we know it doesn't break anything, unless you can provide such info.

Either way, reposting the same error over and over and over again does not help solve this issue. D0by is aware of the issue, yet there is no known fix outside of maybe supressing the error.

**Comment by d0by1** [comment]
Hello, this should now be fixed in version 2.8.15. If you ever encounter this issue again, please create a new issue. Thanks for reporting it and let me know if the fix helped.
