### ISSUE TITLE
Wrong permissions on hologram file causes server crash

### ISSUE THREAD

**Issue by TBG-FR** [DecentSoftware-eu/DecentHolograms#44]
First of all, thanks for that awesome plugin ! Sadly, I had an crash while testing it (and in a early step !), so here it is 😅 

## Information
Minecraft version `1.18.2`
Server type `Purpur`, version `git-Purpur-1616` (latest)

## Steps to reproduce
- Create a file in `/plugins/DecentHolograms/holograms`, for example `example_entity.yml`
- Paste the content found on https://wiki.decentholograms.eu/get-started-1/examples/example-entity
- Run `dh reload` and then `/dh movehere example_entity`
- Logs are full of WARN/ERROR, and then the server crashes 💥 

## Logs
```
[23:48:37] [Server thread/WARN]: java.io.FileNotFoundException: plugins/DecentHolograms/holograms/example_entity.yml (Permission denied)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.open(Unknown Source)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[23:48:37] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:67)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.save(Configuration.java:104)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:93)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.holograms.Hologram.save(Hologram.java:301)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.plugin.commands.HologramSubCommand$HologramMovehereSub.lambda$getCommandHandler$0(HologramSubCommand.java:866)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.commands.DecentCommand.handle(DecentCommand.java:122)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.commands.DecentCommand.handle(DecentCommand.java:114)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.commands.DecentCommand.execute(DecentCommand.java:57)
[23:48:37] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[23:48:37] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2389)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2200)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2181)
[23:48:37] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:48:37] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:48:37] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:48:37] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:48:37] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1426)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[23:48:37] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1403)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1396)
[23:48:37] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1530)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[23:48:37] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[23:48:37] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[23:48:37] [Server thread/INFO]: [DecentHolograms] Attempting to fix error...
[23:48:37] [Server thread/WARN]: java.io.FileNotFoundException: plugins/DecentHolograms/holograms/example_entity.yml (Permission denied)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.open0(Native Method)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.open(Unknown Source)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[23:48:37] [Server thread/WARN]:        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[23:48:37] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:67)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.save(Configuration.java:104)
[23:48:37] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:93)


[...]

[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:40] [Server thread/WARN]:        at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
```

## Behaviour & Fix

I understand that the permissions on my file were wrong (`root` permissions instead of my user), but the hologram still got loaded and displayed, and then when I tried to move it, it caused the crash... There should be something to avoid this, and even maybe displaying an error message (and not the hologram, as if it worked)

I hope I gave you enough information, and if needed I'll be glad to help fixing this 🤙

**Comment by Andre601** [comment]
I doubt there is anything we could do.
Just create the hologram through commands, as it should be done anyway

**Comment by TBG-FR** [comment]
Seeing the examples on the wiki, I tought that was (one of) the right way to do that. I must admit that I try to avoid using commands again and again when a config file with a great syntax does the job 😅 

Anyway, maybe it misses a "fail safe" (try/catch) thing to avoid that, because that means other issues could cause server crash too, no ?

**Comment by Andre601** [comment]
I have a hard time believing that it really is the plugin causing the server to shut down/crash and not a bad behaviour of the server or java itself.

Would be good if you could provide logs, preferably through a site like https://mclo.gs/

**Comment by TBG-FR** [comment]
From what I understand, the plugin is spamming the server, and that's what makes the server crashes, but I think you know more than me on that subject, so here are the logs

The file is so heavy that it made http://mclo.gs page crash in browser, so here is the `.gz` file containing the `.log` file
https://transfer.sh/6yri0T/mclogs_dh_2022-05-05-9.gz

**Comment by Andre601** [comment]
> From what I understand, the plugin is spamming the server, and that's what makes the server crashes, but I think you know more than me on that subject, so here are the logs
> 
> The file is so heavy that it made http://mclo.gs page crash in browser, so here is the `.gz` file containing the `.log` file https://transfer.sh/6yri0T/mclogs_dh_2022-05-05-9.gz

Wow... Good job crashing the page. xD

Tho, tbh out of safety am I not downloading files. Hope you understand that... Maybe a github gist could work?
Alternatively, I guess pasting it in the issue itself as a code block should work too.

**Comment by TBG-FR** [comment]
Thanks ahah 😂 
I fully understand, but the log file is really heavy (191MB)... I'll try to make a version where I remove duplicate lines

In short, the logs display these lines
```
[23:49:06] [Server thread/INFO]: [DecentHolograms] Attempting to fix error...
[23:49:06] [Server thread/WARN]: java.io.FileNotFoundException: plugins/DecentHolograms/holograms/example_entity.yml (Permission denied)
[23:49:06] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[23:49:06] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open(Unknown Source)
[23:49:06] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[23:49:06] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[23:49:06] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:67)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.save(Configuration.java:104)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:93)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
```

Followed by this line, repeated around **200 000 times** at each occurrence 😱 
```
[Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
```

And then it ends with
```
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.utils.config.Configuration.saveData(Configuration.java:98)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.holograms.Hologram.save(Hologram.java:301)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.plugin.commands.HologramSubCommand$HologramMovehereSub.lambda$getCommandHandler$0(HologramSubCommand.java:866)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.commands.DecentCommand.handle(DecentCommand.java:122)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.commands.DecentCommand.handle(DecentCommand.java:114)
[23:49:06] [Server thread/WARN]: 	at DecentHolograms-2.3.1.jar//eu.decentsoftware.holograms.api.commands.DecentCommand.execute(DecentCommand.java:57)
[23:49:06] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[23:49:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[23:49:06] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2389)
```

Here are the first 3000 lines, from the server starting to the error loops : https://mclo.gs/6XDwQ5H

The **whole file is around 1M lines, hence the 191 MB** 😅

**Comment by Andre601** [comment]
I'll see if I can patch this issue somehow...

**Comment by Andre601** [comment]
Alright, from the logs can I see two things that aren't good:

- Usage of `/purpur reload`
- Usage of `/reload`

Those commands print warnings for a reason. You should never use reloads and only use proper restarts.

Other than that did I find the error:
For whatever reason does DH try to (re)create the file and then save it when it fails to save a file, which results in an endless loop.

I made this quick change and would appreciate it, if you could try it (Zip file because GitHub doesn't allow Jar file uploads):
[DecentHolograms-2.3.1.zip](https://github.com/DecentSoftware-eu/DecentHolograms/files/8643209/DecentHolograms-2.3.1.zip)

**Comment by TBG-FR** [comment]
> Alright, from the logs can I see two things that aren't good:
> 
> * Usage of `/purpur reload`
> * Usage of `/reload`
> 
> Those commands print warnings for a reason. You should never use reloads and only use proper restarts.
> 
> Other than that did I find the error: For whatever reason does DH try to (re)create the file and then save it when it fails to save a file, which results in an endless loop.
> 
> It basically does:
> 
> * Call `saveData()`
> * When Success -> Done
> * When Failure -> Call `createData()` followed by `saveData()` (Starts at point one again)
> 
> I made some changes (Basically removed this loop) and would appreciate if you could test it. I have to send it as Zip file because GitHub doesn't allow Jar files as direct uploads: [DecentHolograms-2.3.1.zip](https://github.com/DecentSoftware-eu/DecentHolograms/files/8643209/DecentHolograms-2.3.1.zip)

I admit I've been using reload for years, but usually to test things, and then do a restart when everything is in place 😅 
However, I did the same steps without any reload, and it produced the same result.

Looks like your changes are good, the server isn't crashing anymore using the jar you provided !
```
[01:16:54 INFO]: TBG_FR issued server command: /dh mvhr bad_holo
[01:16:54 WARN]: [DecentHolograms] Error while saving data for holograms/bad_holo.yml: plugins/DecentHolograms/holograms/bad_holo.yml (Permission denied)
```

However the player isn't informed of that, I had a `Hologram has been moved` in chat 😅 

Thanks for the quick answers tho, and good job 💪
