### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [DecentSoftware-eu/DecentHolograms#66]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

DecentHolograms Version: 2.5.3 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

### Feature

I would like to see this was performed asynchronous from the main thread.

### Alternatives

`[13:10:00] [Server thread/WARN]: [LagMonitor] Loaded class eu.decentsoftware.holograms.api.utils.file.FileUtils from DecentHolograms v2.5.3 which is not a depend or softdepend of this plugin.
[13:10:00] [Server thread/WARN]: [LagMonitor] Plugin DecentHolograms is performing a blocking I/O operation (Permission: plugins\DecentHolograms\holograms) on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time. Keep in mind to keep the code thread-safe. Report it to the plugin author
[13:10:00] [Server thread/WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developers to find the source. LagMonitor doesn't prevent this action. It just warns you about it. 
java.lang.IllegalAccessException: null
	at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:65) ~[LagMonitor.jar:?]
	at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:51) ~[LagMonitor.jar:?]
	at com.github.games647.lagmonitor.threading.BlockingSecurityManager.checkMainThreadOperation(BlockingSecurityManager.java:40) ~[LagMonitor.jar:?]
	at com.github.games647.lagmonitor.threading.BlockingSecurityManager.checkPermission(BlockingSecurityManager.java:35) ~[LagMonitor.jar:?]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:756) ~[?:?]
	at java.io.File.exists(File.java:829) ~[?:?]
	at eu.decentsoftware.holograms.api.utils.file.FileUtils.getFileNames(FileUtils.java:24) ~[DecentHolograms-2.5.3.jar:?]
	at eu.decentsoftware.holograms.api.holograms.HologramManager.loadHolograms(HologramManager.java:248) ~[DecentHolograms-2.5.3.jar:?]
	at eu.decentsoftware.holograms.api.holograms.HologramManager.reload(HologramManager.java:135) ~[DecentHolograms-2.5.3.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1762]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1155) ~[purpur-1.19.2.jar:git-Purpur-1762]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1762]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Thanks =D.

**Comment by d0by1** [comment]
Hello,

this should now be very much improved. Let me know if there are any more problems related to this topic.

Thanks for reporting this!

**Comment by d0by1** [comment]
I will now close this, if there are any more problems related to this, feel free to create a new issue.
